---
title: "Project 1 Vignette: Reading In and Exploring Data via an API"
author: "Kelly Baker"
date: "9/10/2020"
output: 
  rmarkdown::github_document:
    toc: true
    toc_depth: 2
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(tidyverse)
library(DT)
```

# Introduction
<br>
This vignette will walk you through how to connect with data through an API. Specifically, we will look at how to access certain endpoints (tables) as well as how join returned datasets, create new variables, and explore the data through basic summarization and graphing.
<br>

## Required Packages
<br>
To get started, we'll need to ensure we have the tools installed and loaded into RStudio to read in, manipulate, summarize, and plot the data. Below is an outline of packages that are required to for this project:
<br>

* **dplyr**: for data manipulation
* **DT**: for creating interactive data tables. 
* **ggplot2**: for plotting and graphing
* **readr**: for reading in data
* **tibble**: for creating special data frames with improved printing properties
* **tidyr**: for reshaping data